baseURL = 'https://evincars.github.io/'
languageCode = 'en-us'
title = 'Evincars blog'
theme = 'binario'


[Params]
  description = "Personal blog for my Angular notes"
  columns = 2
  copyright = "Binario" # Copyright holder, otherwise will use .Site.Title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  mainSections = ["posts"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "" # dark-green, dark-blue, dark-red, dark-violet
# customCSS = ["css/custom.css"] # Include custom CSS files
# customJS = ["js/custom.js"]#  Include custom JS files
# mainMenuAlignment = "right"#  Align main menu (desktop version) to the right side
# authorbox = true # Show auto rbox at bottom of single pages if true
# comments = true # Enable com ents for all site pages
# related = true # Enable Relt ed content for single pages
# relatedMax = 5 # Set the mai mum number of elements that can be displayed in related block. Optional
# mathjax = true # Enable MatJ ax for all site pages
# mathjaxPath = "https://cdnj. cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
# mathjaxConfig = "TeX-AMS-MM_ HTMLorMML" # Specify MathJax config. Optional
# hideNoPostsWarning = false   Don't show no posts empty state warning in main page, if true

[Params.Entry]
  meta = ["date", "categories", "tags"] # Enable meta fields in given order
  toc = true # Enable Table of Contents
  tocOpen = true # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "Home" # Home node text

[Params.Social]
  email = "lasak.ad@gmail.com"
  twitter = "LasakAdam"
  linkedin = "adam-lasak"
  github = "Evincars"

[Params.Share] # Entry Share block
  twitter = true
  reddit = true
  linkedin = true

[Params.Manifest]
  name = "Binario"
  shortName = "Binario"
  display = "browser"
  startUrl = "/"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "Responsive card-based & code-light Hugo theme"
  orientation = "portrait"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]